### ISSUE TITLE
A Offset implementation

### ISSUE THREAD

**Issue by webmarkelov** [hekigan/vue-directive-tooltip#4]
Hi! Very lacking is a **offset** implementation

**Comment by webmarkelov** [comment]
A solution example:
```css
.vue-tooltip {
  top: -3px !important;
}
```
