### ISSUE TITLE
Rendering issue with multi-column CSS

### ISSUE THREAD

**Issue by mikebronner** [hekigan/vue-directive-tooltip#45]
#### Behaviour
When using the tooltip in conjunction with multi-column CSS, the tooltip breaks with the columns, instead of rendering above them.

https://codepen.io/hekigan/pen/BdjJxo

(I was unable to get the tooltips to show using the provided code-pen, but you should get the idea from the code for reproduction.)

The relevant CSS is:
```css
.columns-3 {
    column-count: 3;

    & > * {
        -webkit-column-break-inside: avoid;
        -moz-column-break-inside: avoid;
        -o-column-break-inside: avoid;
        -ms-column-break-inside: avoid;
        column-break-inside: avoid;
    }
}
```

- Browser Version: Safari 13.0
- Operating System: macOS 10.15.0

Any suggestions on what I might try to have the tooltips ignore the multi-column css? Thanks!
